### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by SirLappy** [pophealth/popHealth#41]
I've been trying to install PopHealth for a few days now, unsuccessfully.  I'm using the Installation v2.1 instructions, but there seems to be some errors of some kind.

I believe the installation gets closest when I use the 'install_pophealth.sh' script - everything completes, but then when I try to access the web page, it redirects to /users/sign_in correctly, but the page that comes up is the 500 error page.  I've tried to debug this situation, but have not come up with any solutions.

If I follow the instructions manually instead of using the script, I get an error on the 'bundle install' step when it's attempting to install therubyracer.

I've tried to install all the pieces separately, getting them to work and them bringing it all together, but I can't manage to do that either.

You should be able to duplicate the issues by just following the instructions.  I've done it many times, and it always breaks the same ways.

**Comment by jefflunt** [comment]
Can you post the error message(s) from both the automated and manual steps? Is this still an issue?

**Comment by SirLappy** [comment]
Yes, it is still an issue.

steps I took when running the script:

-installed ubuntu 12.04.1 desktop edition

-ran the following commands:
sudo apt-get update
sudo apt-get upgrade
sudo shutdown -r now

-downloaded the install script, modified permissions to 777 on the install script
-sudo ./install_pophealth.sh

as the install script is running, everything looks good with the exception of:
Install mongodb-10gen: done - incompatible (done in green, incompatible in red)

when the script finishes, I go to step 11, precompile assets

I do more permissions modifying so that I can alter the file in question, and that goes ok

I attempt to log in as pophealth and run:
bundle exec rake assets:precompile
but i get a message saying: 
The program 'bundle' is currently not installed.  You can install it by typing:
sudo apt-get install ruby-bundler

So, i run that command (after switching back to the normal user, as if I try to do it as the pophealth user, it asks for the sudo password for pophealth, which I couldn't figure out how to find), which seems to execute correctly.
Then, I switch back to the pophealth users and try 'bundle exec rake assets:precompile' again, and get the following error:

```
/usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require': no such file to load -- rubygems (LoadError)
from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
from /usr/lib/ruby/vendor_ruby/bundler.rb:11
from /usr/bin/bundle:4:in `require'
from /usr/bin/bundle:4
```

So currently, when I try to go to the website, it just takes me to a page with the url '[ip]/users/sign_in' that says:

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

steps I took when running the manual commands:

-followed all the steps completely, skipping the section dealing with a proxy server

I get an error on the line that says:
rvm use 1.9.3-p385

the error says:
The program 'rvm' is currently not installed.  You can install it by typing:
sudo apt-get install ruby-rvm

So, I run that command.  I get 2 notifications about duplicate files during that install, and choose the default, which is to keep the current version.

I then run 'rvm use 1.9.3-p385' again, and the system reports the following:

```
/usr/local/rvm/scripts/functions/utility_system: line 21: awk: command not found
/usr/local/rvm/scripts/functions/utility_system: line 22: dpkg: command not found
/usr/local/rvm/scripts/functions/utility_system: line 167: tr: command not found
/usr/local/rvm/scripts/functions/support: line 230: awk: command not found
/usr/local/rvm/scripts/functions/support: line 230: awk: command not found
/usr/local/rvm/scripts/functions/support: line 230: awk: command not found
/usr/local/rvm/scripts/functions/utility: line 207: head: command not found
/usr/local/rvm/scripts/functions/utility: line 201: sort: command not found
/usr/local/rvm/scripts/functions/support: line 230: awk: command not found
Using /usr/local/rvm/gems/ruby-1.9.3-p385
/usr/local/rvm/scripts/functions/utility: line 207: head: command not found
/usr/local/rvm/scripts/functions/utility: line 201: sort: command not found
```

...which looks like a failure to me, but I'll continue with the instructions anyway.

The next command, 'rvm --default 1.9.3-p385', also gives a similar set of 'command not found' errors.

continuing on, mongodb seems to install correctly

I get an error on the line:
sudo su - pophealth

the error is:

```
/bin/lesspipe: 1: /bin/lesspipe: basename: not found
/bin/lesspipe: 1: /bin/lesspipe: dirname: not found
/bin/lesspipe: 279: [: =: unexpected operator
Command 'dircolors' is available in '/usr/bin/dircolors'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
dircolors: command not found
```

but, after the error i am logged in as pophealth, so I'll continue

the next line, 'git clone https://github.com/pophealth/popHealth.git', gives me the following error:
Command 'git' is available in '/usr/bin/git'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
git: command not found

so I googled for the answer to that, and seem to have fixed it with this command:
export PATH=/usr/bin:/bin

next, i get another error when trying 'bundle install', the error is:
The program 'bundle' is currently not installed.  You can install it by typing:
sudo apt-get install ruby-bundler

so I run that, and then try 'bundle install' again, and get this error:

```
/usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require': no such file to load -- rubygems (LoadError)
from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
from /usr/lib/ruby/vendor_ruby/bundler.rb:11
from /usr/bin/bundle:4:in `require'
from /usr/bin/bundle:4
```

now, I don't remember what all I had to do to get it a little further, so it bugs out on therubyracer as I was saying 2 months ago when I first entered the bug, but I was trying all sorts of things to get it to work.

Both of these examples were tested in 2 fresh VMs that I made just now.

**Comment by johnrancourt** [comment]
Hey guys - The install script does not work. Rob McCready from Mitre, the team that created the software, explains this in this post from the google group: https://groups.google.com/forum/#!topic/pophealth-talk/ukx4ai6QZfM

It looks like you just have to follow the step-by-step instructions.

**Comment by SirLappy** [comment]
yes, as I pointed out in both of my comments, I have tried both the script and the manual install instructions.  neither work.

**Comment by rdingwell** [comment]
What in the manual instructions is not working?

**Comment by SirLappy** [comment]
manual instructions trial starts with 'steps I took when running the manual commands:', and continues to the bottom of the comment.  CRTL+F this page and you should find it.  my apologies for not knowing how to format better.

**Comment by rdingwell** [comment]
Ok,

I took a quick look at the instructions and there were a couple of items that needed to be updated for the rvm installation.  At the time these were written I believe rvm behaved a little bit differently but has since been updated.

The other thing I see is that you are using Ubuntu Desktop while the instructions were written for Ubuntu Server.  There may well be components that are installed on the Serve edition that are not available by default in the Desktop version

**Comment by SirLappy** [comment]
thanks for the fixes!  the install is going a lot further now, but it still isn't quite there.  I made a fresh vm using the server edition this time (previous testing told me there was no difference, so i tend to go with desktop because it's faster for me), and got smoothly to the very last section.  However I'm still getting an error at the line:

```
bundle exec rake assets:precompile
```

... trying to run it as the pophealth user.

the error is:

```
/usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require': no such file to load -- rubygems (LoadError)
from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
from /usr/lib/ruby/vendor_ruby/bundler.rb:11
from /usr/bin/bundle:4:in `require'
from /usr/bin/bundle:4
```

**Comment by Xodarap** [comment]
@SirLappy: I got an error at that step too (although mine was slightly different). I eventually figured it out: you need to install node.js. You can just run:

> sudo apt-get install nodejs

and it will work.

**Comment by meadj01** [comment]
I am getting stuck at the same point, but with a different error message.  Can anyone help troubleshoot this? See below:
pophealth@parallels-Parallels-Virtual-Platform:~/popHealth$ bundle install
Fetching source index from http://rubygems.org/
Using rake 10.0.3
Using i18n 0.6.3
Using multi_json 1.6.1
Using activesupport 3.2.12
Using builder 3.0.4
Using activemodel 3.2.12
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.2
Using hike 1.2.1
Using tilt 1.3.3
Using sprockets 2.2.2
Using actionpack 3.2.12
Using mime-types 1.21
Using polyglot 0.3.3
Using treetop 1.4.12
Using mail 2.4.4
Using actionmailer 3.2.12
Using arel 3.0.2
Using tzinfo 0.3.35
Using activerecord 3.2.12
Using activeresource 3.2.12
Using ansi 1.4.3
Using bcrypt-ruby 3.0.1
Using sass 3.2.6
Using bootstrap-sass 2.3.0.1
Using cancan 1.6.9
Using choice 0.1.6
Using coderay 1.0.9
Using coffee-script-source 1.5.0
Using execjs 1.4.0
Using coffee-script 2.2.0
Using rack-ssl 1.3.3
Using json 1.7.7
Using rdoc 3.12.2
Using thor 0.17.0
Using railties 3.2.12
Using coffee-rails 3.2.2
Using yamler 0.1.0
Using configatron 2.10.0
Using hashie 2.0.2
Using cover_me 1.2.0
Using daemons 1.1.9
Using delayed_job 3.0.5
Using moped 1.4.2
Using origin 1.0.11
Using mongoid 3.1.2
Using delayed_job_mongoid 2.0.0
Using orm_adapter 0.4.0
Using warden 1.2.1
Using devise 2.2.3
Using ejs 1.1.1
Using eventmachine 1.0.0
Using factory_girl 2.6.3
Using multipart-post 1.2.0
Using faraday 0.8.6
Using foreman 0.61.0
Using formtastic 2.2.1
Using nokogiri 1.5.6
Using oauth 0.4.7
Using httpauth 0.2.0
Using jwt 0.1.5
Using multi_xml 0.5.3
Using oauth2 0.9.1
Using google-spreadsheet-ruby 0.1.8
Using log4r 1.1.10
Using rest-client 1.6.7
Using rubyzip 0.9.9
Using ruby-ole 1.2.11.6
Using spreadsheet 0.6.8
Using todonotes 0.1.1
Using roo 1.10.1
Using systemu 2.5.2
Using macaddr 1.6.1
Using uuid 2.3.7
Using health-data-standards 3.0.3
Using jquery-rails 2.1.4
Using kaminari 0.14.1
Using kgio 2.8.0
Using libv8 3.11.8.13
Using metaclass 0.0.1
Using method_source 0.8.1
Using minitest 4.6.1
Using mocha 0.13.2
Using slop 3.4.3
Using pry 0.9.12
Using rubyXL 1.2.10
Using quality-measure-engine 2.3.0
Using bundler 1.6.1
Using rails 3.2.12
Using rails-backbone 0.9.10
Using raindrops 0.10.0
Using ref 1.0.2
Using sass-rails 3.2.6
/usr/local/rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.6.1/lib/bundler.rb:301: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-1.9.3-p385/bin in PATH, mode 042777

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/local/rvm/rubies/ruby-1.9.3-p385/bin/ruby extconf.rb 
```

checking for main() in -lpthread... yes
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/rvm/rubies/ruby-1.9.3-p385/bin/ruby
    --with-pthreadlib
    --without-pthreadlib
    --enable-debug
    --disable-debug
/usr/local/rvm/gems/ruby-1.9.3-p385/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in `initialize': Permission denied - /usr/local/rvm/gems/ruby-1.9.3-p385/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/.location.yml (Errno::EACCES)
    from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in`open'
    from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in `load!'
    from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/libv8-3.11.8.13-x86_64-linux/lib/libv8.rb:6:in`configure_makefile'
    from extconf.rb:32:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20140405-24188-13o6s0o/therubyracer-0.11.4/gems/therubyracer-0.11.4 for inspection.
Results logged to /tmp/bundler20140405-24188-13o6s0o/therubyracer-0.11.4/extensions/x86_64-linux/1.9.1/therubyracer-0.11.4/gem_make.out
An error occurred while installing therubyracer (0.11.4), and Bundler cannot
continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.

**Comment by jenad1kr** [comment]
I am stuck at the same point. location.rb:15:in `initialize': Permission denied.
Has anyone else encountered the same error? thanks.

**Comment by sunderhaus** [comment]
Since the 2.1 instructions guide you to install RVM system wide (note the 'sudo' in the curl line after it's piped to bash) this restricts the pophealth user from reaching all the necessary binaries if you do not include them in the rvm group.

After installing RVM and you've created your pophealth user run this command:

```
sudo usermod -a -G rvm pophealth
```

Then, if you're currently logged in as pophealth, log out and back in to make the group addition effective. You can then attempt to 'bundle install' again.

**Comment by ivaldes1** [comment]
I followed the step by step installation instructions on Ubuntu 16.04 LTS. When I try to access pophealth from http://<ip address> it gives me 'We're sorry but something went wrong'

/var/log/apache2/error.log says:

*** ERROR ***: Cannot execute /home/pophealth/.rvm/gems: Permission denied (13)

I put in PassengerUser pophealth into apache2 pophealth config file but that did not help.  What can I try next?
